service: vendorm-machine

frameworkVersion: ">=1.3.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

package:
  exclude:
    - src/**
    - coverage/**
    - .vscode/**
    - .dockerignore
    - .editorconfig
    - .env
    - .gitignore
    - Dockerfile
    - README.MD
    - '*.{ts,js,json,yml}'
  include:
    - dist/**
    - '!src/**/*.test.js'
    - '!src/**/*.serverless.yml'

functions:
  getInitialBalance:
    handler: dist/api/index.getInitialBalance
    events:
      - http: 
          path: /initial-balance
          method: get
          cors:
            origin: '*'
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false 
  calculateChange:
    handler: dist/api/index.calculateChange
    events:
      - http:
          path: /calculate-change
          method: post
          cors:
            origin: '*'
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false 

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0 
