service: change-service

frameworkVersion: ">=1.3.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

package:
  exclude:
    - src/**
    - coverage/**
    - .vscode/**
    - .dockerignore
    - .editorconfig
    - .env
    - .gitignore
    - Dockerfile
    - README.MD
    - '*.{ts,js,json,yml}'
  include:
    - dist/**
    - '!src/**/*.test.js'
    - '!src/**/*.serverless.yml'

functions:
  - '${file(dist/api/handlers.serverless.yml)}'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0 